/*
 * AppCfg.h
 *
 * Created: 06.08.2019 15:58:25
 *  Author: Pascal Romahn
 */ 

#include "CfgGenMacros.h"

OS_CONFIG_TASK_BEGIN
    OS_CONFIG_TASK_DEF(Idle, 0, 64, 1, AUTOSTART,    EXTENDED, PREEMPTIVE)
    OS_CONFIG_TASK_DEF(T1,   5, 128, 1, AUTOSTART,    BASIC, NON_PREEMPTIVE)
    OS_CONFIG_TASK_DEF(T2,   6, 128, 1, AUTOSTART,    BASIC, NON_PREEMPTIVE)
    OS_CONFIG_TASK_DEF(T3,   8, 32, 1, AUTOSTART,    EXTENDED, PREEMPTIVE)
OS_CONFIG_TASK_END
